services:
  multilingual-tts:
    image: python:3.12
    entrypoint: tail -f /dev/null
    working_dir: /app
    container_name: multilingual-tts
    volumes:
      - ./Multilingual-TTS:/app
    ports:
      - "7860:7860"